namespace Sistema_de_Gerenciamento.Forms
{
    partial class Forms_ConfiguracaoGerencial
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Forms_ConfiguracaoGerencial));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.btnComissaoPorProduto = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDescontoPoPagamentoAvista = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDescontoPorGrupoSubGrupoProdutos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnConfiguracaoGerencialPagamentoCarne = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFechar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnJurosPorPagamentoaCredito = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // btnComissaoPorProduto
            // 
            this.btnComissaoPorProduto.AllowAnimations = true;
            this.btnComissaoPorProduto.AllowMouseEffects = true;
            this.btnComissaoPorProduto.AllowToggling = false;
            this.btnComissaoPorProduto.AnimationSpeed = 200;
            this.btnComissaoPorProduto.AutoGenerateColors = false;
            this.btnComissaoPorProduto.AutoRoundBorders = false;
            this.btnComissaoPorProduto.AutoSizeLeftIcon = true;
            this.btnComissaoPorProduto.AutoSizeRightIcon = true;
            this.btnComissaoPorProduto.BackColor = System.Drawing.Color.Transparent;
            this.btnComissaoPorProduto.BackColor1 = System.Drawing.Color.Transparent;
            this.btnComissaoPorProduto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnComissaoPorProduto.BackgroundImage")));
            this.btnComissaoPorProduto.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComissaoPorProduto.ButtonText = "Comissão Por Produto";
            this.btnComissaoPorProduto.ButtonTextMarginLeft = 0;
            this.btnComissaoPorProduto.ColorContrastOnClick = 45;
            this.btnComissaoPorProduto.ColorContrastOnHover = 45;
            this.btnComissaoPorProduto.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnComissaoPorProduto.CustomizableEdges = borderEdges1;
            this.btnComissaoPorProduto.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnComissaoPorProduto.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnComissaoPorProduto.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnComissaoPorProduto.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnComissaoPorProduto.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnComissaoPorProduto.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnComissaoPorProduto.ForeColor = System.Drawing.Color.Black;
            this.btnComissaoPorProduto.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnComissaoPorProduto.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnComissaoPorProduto.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnComissaoPorProduto.IconMarginLeft = 11;
            this.btnComissaoPorProduto.IconPadding = 10;
            this.btnComissaoPorProduto.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnComissaoPorProduto.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnComissaoPorProduto.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnComissaoPorProduto.IconSize = 25;
            this.btnComissaoPorProduto.IdleBorderColor = System.Drawing.Color.Black;
            this.btnComissaoPorProduto.IdleBorderRadius = 1;
            this.btnComissaoPorProduto.IdleBorderThickness = 1;
            this.btnComissaoPorProduto.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnComissaoPorProduto.IdleIconLeftImage = null;
            this.btnComissaoPorProduto.IdleIconRightImage = null;
            this.btnComissaoPorProduto.IndicateFocus = false;
            this.btnComissaoPorProduto.Location = new System.Drawing.Point(30, 100);
            this.btnComissaoPorProduto.Name = "btnComissaoPorProduto";
            this.btnComissaoPorProduto.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnComissaoPorProduto.OnDisabledState.BorderRadius = 1;
            this.btnComissaoPorProduto.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComissaoPorProduto.OnDisabledState.BorderThickness = 1;
            this.btnComissaoPorProduto.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnComissaoPorProduto.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnComissaoPorProduto.OnDisabledState.IconLeftImage = null;
            this.btnComissaoPorProduto.OnDisabledState.IconRightImage = null;
            this.btnComissaoPorProduto.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnComissaoPorProduto.onHoverState.BorderRadius = 1;
            this.btnComissaoPorProduto.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComissaoPorProduto.onHoverState.BorderThickness = 1;
            this.btnComissaoPorProduto.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnComissaoPorProduto.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnComissaoPorProduto.onHoverState.IconLeftImage = null;
            this.btnComissaoPorProduto.onHoverState.IconRightImage = null;
            this.btnComissaoPorProduto.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnComissaoPorProduto.OnIdleState.BorderRadius = 1;
            this.btnComissaoPorProduto.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComissaoPorProduto.OnIdleState.BorderThickness = 1;
            this.btnComissaoPorProduto.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnComissaoPorProduto.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnComissaoPorProduto.OnIdleState.IconLeftImage = null;
            this.btnComissaoPorProduto.OnIdleState.IconRightImage = null;
            this.btnComissaoPorProduto.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnComissaoPorProduto.OnPressedState.BorderRadius = 1;
            this.btnComissaoPorProduto.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnComissaoPorProduto.OnPressedState.BorderThickness = 1;
            this.btnComissaoPorProduto.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnComissaoPorProduto.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnComissaoPorProduto.OnPressedState.IconLeftImage = null;
            this.btnComissaoPorProduto.OnPressedState.IconRightImage = null;
            this.btnComissaoPorProduto.Size = new System.Drawing.Size(299, 39);
            this.btnComissaoPorProduto.TabIndex = 255;
            this.btnComissaoPorProduto.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnComissaoPorProduto.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnComissaoPorProduto.TextMarginLeft = 0;
            this.btnComissaoPorProduto.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnComissaoPorProduto.UseDefaultRadiusAndThickness = true;
            this.btnComissaoPorProduto.Click += new System.EventHandler(this.btnComissaoPorProduto_Click);
            // 
            // btnDescontoPoPagamentoAvista
            // 
            this.btnDescontoPoPagamentoAvista.AllowAnimations = true;
            this.btnDescontoPoPagamentoAvista.AllowMouseEffects = true;
            this.btnDescontoPoPagamentoAvista.AllowToggling = false;
            this.btnDescontoPoPagamentoAvista.AnimationSpeed = 200;
            this.btnDescontoPoPagamentoAvista.AutoGenerateColors = false;
            this.btnDescontoPoPagamentoAvista.AutoRoundBorders = false;
            this.btnDescontoPoPagamentoAvista.AutoSizeLeftIcon = true;
            this.btnDescontoPoPagamentoAvista.AutoSizeRightIcon = true;
            this.btnDescontoPoPagamentoAvista.BackColor = System.Drawing.Color.Transparent;
            this.btnDescontoPoPagamentoAvista.BackColor1 = System.Drawing.Color.Transparent;
            this.btnDescontoPoPagamentoAvista.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDescontoPoPagamentoAvista.BackgroundImage")));
            this.btnDescontoPoPagamentoAvista.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPoPagamentoAvista.ButtonText = "Desconto Por Pagamento Avista";
            this.btnDescontoPoPagamentoAvista.ButtonTextMarginLeft = 0;
            this.btnDescontoPoPagamentoAvista.ColorContrastOnClick = 45;
            this.btnDescontoPoPagamentoAvista.ColorContrastOnHover = 45;
            this.btnDescontoPoPagamentoAvista.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnDescontoPoPagamentoAvista.CustomizableEdges = borderEdges2;
            this.btnDescontoPoPagamentoAvista.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDescontoPoPagamentoAvista.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDescontoPoPagamentoAvista.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDescontoPoPagamentoAvista.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDescontoPoPagamentoAvista.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDescontoPoPagamentoAvista.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDescontoPoPagamentoAvista.ForeColor = System.Drawing.Color.Black;
            this.btnDescontoPoPagamentoAvista.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDescontoPoPagamentoAvista.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDescontoPoPagamentoAvista.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDescontoPoPagamentoAvista.IconMarginLeft = 11;
            this.btnDescontoPoPagamentoAvista.IconPadding = 10;
            this.btnDescontoPoPagamentoAvista.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDescontoPoPagamentoAvista.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDescontoPoPagamentoAvista.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDescontoPoPagamentoAvista.IconSize = 25;
            this.btnDescontoPoPagamentoAvista.IdleBorderColor = System.Drawing.Color.Black;
            this.btnDescontoPoPagamentoAvista.IdleBorderRadius = 1;
            this.btnDescontoPoPagamentoAvista.IdleBorderThickness = 1;
            this.btnDescontoPoPagamentoAvista.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnDescontoPoPagamentoAvista.IdleIconLeftImage = null;
            this.btnDescontoPoPagamentoAvista.IdleIconRightImage = null;
            this.btnDescontoPoPagamentoAvista.IndicateFocus = false;
            this.btnDescontoPoPagamentoAvista.Location = new System.Drawing.Point(30, 175);
            this.btnDescontoPoPagamentoAvista.Name = "btnDescontoPoPagamentoAvista";
            this.btnDescontoPoPagamentoAvista.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDescontoPoPagamentoAvista.OnDisabledState.BorderRadius = 1;
            this.btnDescontoPoPagamentoAvista.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPoPagamentoAvista.OnDisabledState.BorderThickness = 1;
            this.btnDescontoPoPagamentoAvista.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDescontoPoPagamentoAvista.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDescontoPoPagamentoAvista.OnDisabledState.IconLeftImage = null;
            this.btnDescontoPoPagamentoAvista.OnDisabledState.IconRightImage = null;
            this.btnDescontoPoPagamentoAvista.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDescontoPoPagamentoAvista.onHoverState.BorderRadius = 1;
            this.btnDescontoPoPagamentoAvista.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPoPagamentoAvista.onHoverState.BorderThickness = 1;
            this.btnDescontoPoPagamentoAvista.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDescontoPoPagamentoAvista.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDescontoPoPagamentoAvista.onHoverState.IconLeftImage = null;
            this.btnDescontoPoPagamentoAvista.onHoverState.IconRightImage = null;
            this.btnDescontoPoPagamentoAvista.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnDescontoPoPagamentoAvista.OnIdleState.BorderRadius = 1;
            this.btnDescontoPoPagamentoAvista.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPoPagamentoAvista.OnIdleState.BorderThickness = 1;
            this.btnDescontoPoPagamentoAvista.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnDescontoPoPagamentoAvista.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnDescontoPoPagamentoAvista.OnIdleState.IconLeftImage = null;
            this.btnDescontoPoPagamentoAvista.OnIdleState.IconRightImage = null;
            this.btnDescontoPoPagamentoAvista.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDescontoPoPagamentoAvista.OnPressedState.BorderRadius = 1;
            this.btnDescontoPoPagamentoAvista.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPoPagamentoAvista.OnPressedState.BorderThickness = 1;
            this.btnDescontoPoPagamentoAvista.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDescontoPoPagamentoAvista.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDescontoPoPagamentoAvista.OnPressedState.IconLeftImage = null;
            this.btnDescontoPoPagamentoAvista.OnPressedState.IconRightImage = null;
            this.btnDescontoPoPagamentoAvista.Size = new System.Drawing.Size(299, 39);
            this.btnDescontoPoPagamentoAvista.TabIndex = 254;
            this.btnDescontoPoPagamentoAvista.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDescontoPoPagamentoAvista.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDescontoPoPagamentoAvista.TextMarginLeft = 0;
            this.btnDescontoPoPagamentoAvista.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDescontoPoPagamentoAvista.UseDefaultRadiusAndThickness = true;
            this.btnDescontoPoPagamentoAvista.Click += new System.EventHandler(this.btnDescontoPoPagamentoAvista_Click);
            // 
            // btnDescontoPorGrupoSubGrupoProdutos
            // 
            this.btnDescontoPorGrupoSubGrupoProdutos.AllowAnimations = true;
            this.btnDescontoPorGrupoSubGrupoProdutos.AllowMouseEffects = true;
            this.btnDescontoPorGrupoSubGrupoProdutos.AllowToggling = false;
            this.btnDescontoPorGrupoSubGrupoProdutos.AnimationSpeed = 200;
            this.btnDescontoPorGrupoSubGrupoProdutos.AutoGenerateColors = false;
            this.btnDescontoPorGrupoSubGrupoProdutos.AutoRoundBorders = false;
            this.btnDescontoPorGrupoSubGrupoProdutos.AutoSizeLeftIcon = true;
            this.btnDescontoPorGrupoSubGrupoProdutos.AutoSizeRightIcon = true;
            this.btnDescontoPorGrupoSubGrupoProdutos.BackColor = System.Drawing.Color.Transparent;
            this.btnDescontoPorGrupoSubGrupoProdutos.BackColor1 = System.Drawing.Color.Transparent;
            this.btnDescontoPorGrupoSubGrupoProdutos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDescontoPorGrupoSubGrupoProdutos.BackgroundImage")));
            this.btnDescontoPorGrupoSubGrupoProdutos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPorGrupoSubGrupoProdutos.ButtonText = "Desconto Por Grupo e Sub-Grupo de Produtos";
            this.btnDescontoPorGrupoSubGrupoProdutos.ButtonTextMarginLeft = 0;
            this.btnDescontoPorGrupoSubGrupoProdutos.ColorContrastOnClick = 45;
            this.btnDescontoPorGrupoSubGrupoProdutos.ColorContrastOnHover = 45;
            this.btnDescontoPorGrupoSubGrupoProdutos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnDescontoPorGrupoSubGrupoProdutos.CustomizableEdges = borderEdges3;
            this.btnDescontoPorGrupoSubGrupoProdutos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDescontoPorGrupoSubGrupoProdutos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDescontoPorGrupoSubGrupoProdutos.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDescontoPorGrupoSubGrupoProdutos.ForeColor = System.Drawing.Color.Black;
            this.btnDescontoPorGrupoSubGrupoProdutos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDescontoPorGrupoSubGrupoProdutos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDescontoPorGrupoSubGrupoProdutos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDescontoPorGrupoSubGrupoProdutos.IconMarginLeft = 11;
            this.btnDescontoPorGrupoSubGrupoProdutos.IconPadding = 10;
            this.btnDescontoPorGrupoSubGrupoProdutos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDescontoPorGrupoSubGrupoProdutos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDescontoPorGrupoSubGrupoProdutos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDescontoPorGrupoSubGrupoProdutos.IconSize = 25;
            this.btnDescontoPorGrupoSubGrupoProdutos.IdleBorderColor = System.Drawing.Color.Black;
            this.btnDescontoPorGrupoSubGrupoProdutos.IdleBorderRadius = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.IdleBorderThickness = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnDescontoPorGrupoSubGrupoProdutos.IdleIconLeftImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.IdleIconRightImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.IndicateFocus = false;
            this.btnDescontoPorGrupoSubGrupoProdutos.Location = new System.Drawing.Point(30, 255);
            this.btnDescontoPorGrupoSubGrupoProdutos.Name = "btnDescontoPorGrupoSubGrupoProdutos";
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.BorderRadius = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.BorderThickness = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.IconLeftImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnDisabledState.IconRightImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.BorderRadius = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.BorderThickness = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.IconLeftImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.onHoverState.IconRightImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.BorderRadius = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.BorderThickness = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.IconLeftImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnIdleState.IconRightImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.BorderRadius = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.BorderThickness = 1;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.IconLeftImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.OnPressedState.IconRightImage = null;
            this.btnDescontoPorGrupoSubGrupoProdutos.Size = new System.Drawing.Size(299, 39);
            this.btnDescontoPorGrupoSubGrupoProdutos.TabIndex = 253;
            this.btnDescontoPorGrupoSubGrupoProdutos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDescontoPorGrupoSubGrupoProdutos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDescontoPorGrupoSubGrupoProdutos.TextMarginLeft = 0;
            this.btnDescontoPorGrupoSubGrupoProdutos.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDescontoPorGrupoSubGrupoProdutos.UseDefaultRadiusAndThickness = true;
            this.btnDescontoPorGrupoSubGrupoProdutos.Click += new System.EventHandler(this.btnDescontoPorGrupoSubGrupoProdutos_Click);
            // 
            // btnConfiguracaoGerencialPagamentoCarne
            // 
            this.btnConfiguracaoGerencialPagamentoCarne.AllowAnimations = true;
            this.btnConfiguracaoGerencialPagamentoCarne.AllowMouseEffects = true;
            this.btnConfiguracaoGerencialPagamentoCarne.AllowToggling = false;
            this.btnConfiguracaoGerencialPagamentoCarne.AnimationSpeed = 200;
            this.btnConfiguracaoGerencialPagamentoCarne.AutoGenerateColors = false;
            this.btnConfiguracaoGerencialPagamentoCarne.AutoRoundBorders = false;
            this.btnConfiguracaoGerencialPagamentoCarne.AutoSizeLeftIcon = true;
            this.btnConfiguracaoGerencialPagamentoCarne.AutoSizeRightIcon = true;
            this.btnConfiguracaoGerencialPagamentoCarne.BackColor = System.Drawing.Color.Transparent;
            this.btnConfiguracaoGerencialPagamentoCarne.BackColor1 = System.Drawing.Color.Transparent;
            this.btnConfiguracaoGerencialPagamentoCarne.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnConfiguracaoGerencialPagamentoCarne.BackgroundImage")));
            this.btnConfiguracaoGerencialPagamentoCarne.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfiguracaoGerencialPagamentoCarne.ButtonText = "Configuracao Gerencial Pagamento Carnê";
            this.btnConfiguracaoGerencialPagamentoCarne.ButtonTextMarginLeft = 0;
            this.btnConfiguracaoGerencialPagamentoCarne.ColorContrastOnClick = 45;
            this.btnConfiguracaoGerencialPagamentoCarne.ColorContrastOnHover = 45;
            this.btnConfiguracaoGerencialPagamentoCarne.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnConfiguracaoGerencialPagamentoCarne.CustomizableEdges = borderEdges4;
            this.btnConfiguracaoGerencialPagamentoCarne.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnConfiguracaoGerencialPagamentoCarne.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfiguracaoGerencialPagamentoCarne.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfiguracaoGerencialPagamentoCarne.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfiguracaoGerencialPagamentoCarne.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnConfiguracaoGerencialPagamentoCarne.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnConfiguracaoGerencialPagamentoCarne.ForeColor = System.Drawing.Color.Black;
            this.btnConfiguracaoGerencialPagamentoCarne.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnConfiguracaoGerencialPagamentoCarne.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfiguracaoGerencialPagamentoCarne.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnConfiguracaoGerencialPagamentoCarne.IconMarginLeft = 11;
            this.btnConfiguracaoGerencialPagamentoCarne.IconPadding = 10;
            this.btnConfiguracaoGerencialPagamentoCarne.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConfiguracaoGerencialPagamentoCarne.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfiguracaoGerencialPagamentoCarne.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnConfiguracaoGerencialPagamentoCarne.IconSize = 25;
            this.btnConfiguracaoGerencialPagamentoCarne.IdleBorderColor = System.Drawing.Color.Black;
            this.btnConfiguracaoGerencialPagamentoCarne.IdleBorderRadius = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.IdleBorderThickness = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnConfiguracaoGerencialPagamentoCarne.IdleIconLeftImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.IdleIconRightImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.IndicateFocus = false;
            this.btnConfiguracaoGerencialPagamentoCarne.Location = new System.Drawing.Point(30, 339);
            this.btnConfiguracaoGerencialPagamentoCarne.Name = "btnConfiguracaoGerencialPagamentoCarne";
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.BorderRadius = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.BorderThickness = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.IconLeftImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.OnDisabledState.IconRightImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.BorderRadius = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.BorderThickness = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.IconLeftImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.onHoverState.IconRightImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.BorderRadius = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.BorderThickness = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.IconLeftImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.OnIdleState.IconRightImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.BorderRadius = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.BorderThickness = 1;
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.IconLeftImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.OnPressedState.IconRightImage = null;
            this.btnConfiguracaoGerencialPagamentoCarne.Size = new System.Drawing.Size(299, 39);
            this.btnConfiguracaoGerencialPagamentoCarne.TabIndex = 252;
            this.btnConfiguracaoGerencialPagamentoCarne.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnConfiguracaoGerencialPagamentoCarne.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnConfiguracaoGerencialPagamentoCarne.TextMarginLeft = 0;
            this.btnConfiguracaoGerencialPagamentoCarne.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnConfiguracaoGerencialPagamentoCarne.UseDefaultRadiusAndThickness = true;
            this.btnConfiguracaoGerencialPagamentoCarne.Click += new System.EventHandler(this.btnConfiguracaoGerencialPagamentoCarne_Click);
            // 
            // btnFechar
            // 
            this.btnFechar.AllowAnimations = true;
            this.btnFechar.AllowMouseEffects = true;
            this.btnFechar.AllowToggling = false;
            this.btnFechar.AnimationSpeed = 200;
            this.btnFechar.AutoGenerateColors = false;
            this.btnFechar.AutoRoundBorders = false;
            this.btnFechar.AutoSizeLeftIcon = true;
            this.btnFechar.AutoSizeRightIcon = true;
            this.btnFechar.BackColor = System.Drawing.Color.Transparent;
            this.btnFechar.BackColor1 = System.Drawing.Color.Transparent;
            this.btnFechar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFechar.BackgroundImage")));
            this.btnFechar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.ButtonText = "(Esc) Fechar";
            this.btnFechar.ButtonTextMarginLeft = 0;
            this.btnFechar.ColorContrastOnClick = 45;
            this.btnFechar.ColorContrastOnHover = 45;
            this.btnFechar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnFechar.CustomizableEdges = borderEdges5;
            this.btnFechar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFechar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFechar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFechar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFechar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFechar.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFechar.ForeColor = System.Drawing.Color.Black;
            this.btnFechar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFechar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFechar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFechar.IconMarginLeft = 11;
            this.btnFechar.IconPadding = 10;
            this.btnFechar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFechar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFechar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFechar.IconSize = 25;
            this.btnFechar.IdleBorderColor = System.Drawing.Color.Black;
            this.btnFechar.IdleBorderRadius = 1;
            this.btnFechar.IdleBorderThickness = 1;
            this.btnFechar.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnFechar.IdleIconLeftImage = null;
            this.btnFechar.IdleIconRightImage = null;
            this.btnFechar.IndicateFocus = false;
            this.btnFechar.Location = new System.Drawing.Point(88, 421);
            this.btnFechar.Name = "btnFechar";
            this.btnFechar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFechar.OnDisabledState.BorderRadius = 1;
            this.btnFechar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.OnDisabledState.BorderThickness = 1;
            this.btnFechar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFechar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFechar.OnDisabledState.IconLeftImage = null;
            this.btnFechar.OnDisabledState.IconRightImage = null;
            this.btnFechar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFechar.onHoverState.BorderRadius = 1;
            this.btnFechar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.onHoverState.BorderThickness = 1;
            this.btnFechar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFechar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFechar.onHoverState.IconLeftImage = null;
            this.btnFechar.onHoverState.IconRightImage = null;
            this.btnFechar.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnFechar.OnIdleState.BorderRadius = 1;
            this.btnFechar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.OnIdleState.BorderThickness = 1;
            this.btnFechar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnFechar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnFechar.OnIdleState.IconLeftImage = null;
            this.btnFechar.OnIdleState.IconRightImage = null;
            this.btnFechar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFechar.OnPressedState.BorderRadius = 1;
            this.btnFechar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.OnPressedState.BorderThickness = 1;
            this.btnFechar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFechar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFechar.OnPressedState.IconLeftImage = null;
            this.btnFechar.OnPressedState.IconRightImage = null;
            this.btnFechar.Size = new System.Drawing.Size(187, 39);
            this.btnFechar.TabIndex = 242;
            this.btnFechar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFechar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFechar.TextMarginLeft = 0;
            this.btnFechar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFechar.UseDefaultRadiusAndThickness = true;
            this.btnFechar.Click += new System.EventHandler(this.btnFechar_Click);
            // 
            // btnJurosPorPagamentoaCredito
            // 
            this.btnJurosPorPagamentoaCredito.AllowAnimations = true;
            this.btnJurosPorPagamentoaCredito.AllowMouseEffects = true;
            this.btnJurosPorPagamentoaCredito.AllowToggling = false;
            this.btnJurosPorPagamentoaCredito.AnimationSpeed = 200;
            this.btnJurosPorPagamentoaCredito.AutoGenerateColors = false;
            this.btnJurosPorPagamentoaCredito.AutoRoundBorders = false;
            this.btnJurosPorPagamentoaCredito.AutoSizeLeftIcon = true;
            this.btnJurosPorPagamentoaCredito.AutoSizeRightIcon = true;
            this.btnJurosPorPagamentoaCredito.BackColor = System.Drawing.Color.Transparent;
            this.btnJurosPorPagamentoaCredito.BackColor1 = System.Drawing.Color.Transparent;
            this.btnJurosPorPagamentoaCredito.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnJurosPorPagamentoaCredito.BackgroundImage")));
            this.btnJurosPorPagamentoaCredito.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJurosPorPagamentoaCredito.ButtonText = "Juros Por Pagamento a Credito";
            this.btnJurosPorPagamentoaCredito.ButtonTextMarginLeft = 0;
            this.btnJurosPorPagamentoaCredito.ColorContrastOnClick = 45;
            this.btnJurosPorPagamentoaCredito.ColorContrastOnHover = 45;
            this.btnJurosPorPagamentoaCredito.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnJurosPorPagamentoaCredito.CustomizableEdges = borderEdges6;
            this.btnJurosPorPagamentoaCredito.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnJurosPorPagamentoaCredito.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJurosPorPagamentoaCredito.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJurosPorPagamentoaCredito.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJurosPorPagamentoaCredito.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnJurosPorPagamentoaCredito.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnJurosPorPagamentoaCredito.ForeColor = System.Drawing.Color.Black;
            this.btnJurosPorPagamentoaCredito.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnJurosPorPagamentoaCredito.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnJurosPorPagamentoaCredito.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnJurosPorPagamentoaCredito.IconMarginLeft = 11;
            this.btnJurosPorPagamentoaCredito.IconPadding = 10;
            this.btnJurosPorPagamentoaCredito.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnJurosPorPagamentoaCredito.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnJurosPorPagamentoaCredito.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnJurosPorPagamentoaCredito.IconSize = 25;
            this.btnJurosPorPagamentoaCredito.IdleBorderColor = System.Drawing.Color.Black;
            this.btnJurosPorPagamentoaCredito.IdleBorderRadius = 1;
            this.btnJurosPorPagamentoaCredito.IdleBorderThickness = 1;
            this.btnJurosPorPagamentoaCredito.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnJurosPorPagamentoaCredito.IdleIconLeftImage = null;
            this.btnJurosPorPagamentoaCredito.IdleIconRightImage = null;
            this.btnJurosPorPagamentoaCredito.IndicateFocus = false;
            this.btnJurosPorPagamentoaCredito.Location = new System.Drawing.Point(30, 27);
            this.btnJurosPorPagamentoaCredito.Name = "btnJurosPorPagamentoaCredito";
            this.btnJurosPorPagamentoaCredito.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnJurosPorPagamentoaCredito.OnDisabledState.BorderRadius = 1;
            this.btnJurosPorPagamentoaCredito.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJurosPorPagamentoaCredito.OnDisabledState.BorderThickness = 1;
            this.btnJurosPorPagamentoaCredito.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnJurosPorPagamentoaCredito.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnJurosPorPagamentoaCredito.OnDisabledState.IconLeftImage = null;
            this.btnJurosPorPagamentoaCredito.OnDisabledState.IconRightImage = null;
            this.btnJurosPorPagamentoaCredito.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnJurosPorPagamentoaCredito.onHoverState.BorderRadius = 1;
            this.btnJurosPorPagamentoaCredito.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJurosPorPagamentoaCredito.onHoverState.BorderThickness = 1;
            this.btnJurosPorPagamentoaCredito.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnJurosPorPagamentoaCredito.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnJurosPorPagamentoaCredito.onHoverState.IconLeftImage = null;
            this.btnJurosPorPagamentoaCredito.onHoverState.IconRightImage = null;
            this.btnJurosPorPagamentoaCredito.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnJurosPorPagamentoaCredito.OnIdleState.BorderRadius = 1;
            this.btnJurosPorPagamentoaCredito.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJurosPorPagamentoaCredito.OnIdleState.BorderThickness = 1;
            this.btnJurosPorPagamentoaCredito.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnJurosPorPagamentoaCredito.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnJurosPorPagamentoaCredito.OnIdleState.IconLeftImage = null;
            this.btnJurosPorPagamentoaCredito.OnIdleState.IconRightImage = null;
            this.btnJurosPorPagamentoaCredito.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnJurosPorPagamentoaCredito.OnPressedState.BorderRadius = 1;
            this.btnJurosPorPagamentoaCredito.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnJurosPorPagamentoaCredito.OnPressedState.BorderThickness = 1;
            this.btnJurosPorPagamentoaCredito.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnJurosPorPagamentoaCredito.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnJurosPorPagamentoaCredito.OnPressedState.IconLeftImage = null;
            this.btnJurosPorPagamentoaCredito.OnPressedState.IconRightImage = null;
            this.btnJurosPorPagamentoaCredito.Size = new System.Drawing.Size(299, 39);
            this.btnJurosPorPagamentoaCredito.TabIndex = 256;
            this.btnJurosPorPagamentoaCredito.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnJurosPorPagamentoaCredito.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnJurosPorPagamentoaCredito.TextMarginLeft = 0;
            this.btnJurosPorPagamentoaCredito.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnJurosPorPagamentoaCredito.UseDefaultRadiusAndThickness = true;
            this.btnJurosPorPagamentoaCredito.Click += new System.EventHandler(this.btnJurosPorPagamentoaCredito_Click);
            // 
            // Forms_ConfiguracaoGerencial
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(381, 487);
            this.Controls.Add(this.btnJurosPorPagamentoaCredito);
            this.Controls.Add(this.btnComissaoPorProduto);
            this.Controls.Add(this.btnDescontoPoPagamentoAvista);
            this.Controls.Add(this.btnDescontoPorGrupoSubGrupoProdutos);
            this.Controls.Add(this.btnConfiguracaoGerencialPagamentoCarne);
            this.Controls.Add(this.btnFechar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.Name = "Forms_ConfiguracaoGerencial";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Configurações Gerenciais";
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Forms_ConfiguracaoGerencial_KeyDown);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFechar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnConfiguracaoGerencialPagamentoCarne;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDescontoPorGrupoSubGrupoProdutos;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDescontoPoPagamentoAvista;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnComissaoPorProduto;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnJurosPorPagamentoaCredito;
    }
}