namespace Sistema_de_Gerenciamento.Forms
{
    partial class Forms_ConsultaEstoqueDetalhada
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Forms_ConsultaEstoqueDetalhada));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.label2 = new System.Windows.Forms.Label();
            this.txtNumeroNFEntrada = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.txtDataEntrada = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCodBarras = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCodProduto = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDescricao = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtQuantidade = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUnidade = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtValorUnitario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStatus = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtRejeitatoPor = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnFechar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.logoSistema1 = new Sistema_de_Gerenciamento.LogoSistema();
            this.SuspendLayout();
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(14, 9);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(85, 15);
            this.label2.TabIndex = 189;
            this.label2.Text = "Nº NF Entrada";
            // 
            // txtNumeroNFEntrada
            // 
            this.txtNumeroNFEntrada.AcceptsReturn = false;
            this.txtNumeroNFEntrada.AcceptsTab = false;
            this.txtNumeroNFEntrada.AnimationSpeed = 200;
            this.txtNumeroNFEntrada.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNumeroNFEntrada.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNumeroNFEntrada.BackColor = System.Drawing.Color.Transparent;
            this.txtNumeroNFEntrada.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNumeroNFEntrada.BackgroundImage")));
            this.txtNumeroNFEntrada.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNumeroNFEntrada.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNumeroNFEntrada.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNumeroNFEntrada.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNumeroNFEntrada.BorderRadius = 1;
            this.txtNumeroNFEntrada.BorderThickness = 1;
            this.txtNumeroNFEntrada.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNumeroNFEntrada.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroNFEntrada.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNumeroNFEntrada.DefaultText = "";
            this.txtNumeroNFEntrada.Enabled = false;
            this.txtNumeroNFEntrada.FillColor = System.Drawing.Color.White;
            this.txtNumeroNFEntrada.HideSelection = true;
            this.txtNumeroNFEntrada.IconLeft = null;
            this.txtNumeroNFEntrada.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroNFEntrada.IconPadding = 10;
            this.txtNumeroNFEntrada.IconRight = null;
            this.txtNumeroNFEntrada.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroNFEntrada.Lines = new string[0];
            this.txtNumeroNFEntrada.Location = new System.Drawing.Point(17, 27);
            this.txtNumeroNFEntrada.MaxLength = 32767;
            this.txtNumeroNFEntrada.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNumeroNFEntrada.Modified = false;
            this.txtNumeroNFEntrada.Multiline = false;
            this.txtNumeroNFEntrada.Name = "txtNumeroNFEntrada";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroNFEntrada.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNumeroNFEntrada.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroNFEntrada.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroNFEntrada.OnIdleState = stateProperties4;
            this.txtNumeroNFEntrada.Padding = new System.Windows.Forms.Padding(3);
            this.txtNumeroNFEntrada.PasswordChar = '\0';
            this.txtNumeroNFEntrada.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNumeroNFEntrada.PlaceholderText = "";
            this.txtNumeroNFEntrada.ReadOnly = false;
            this.txtNumeroNFEntrada.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNumeroNFEntrada.SelectedText = "";
            this.txtNumeroNFEntrada.SelectionLength = 0;
            this.txtNumeroNFEntrada.SelectionStart = 0;
            this.txtNumeroNFEntrada.ShortcutsEnabled = false;
            this.txtNumeroNFEntrada.Size = new System.Drawing.Size(130, 28);
            this.txtNumeroNFEntrada.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNumeroNFEntrada.TabIndex = 190;
            this.txtNumeroNFEntrada.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNumeroNFEntrada.TextMarginBottom = 0;
            this.txtNumeroNFEntrada.TextMarginLeft = 3;
            this.txtNumeroNFEntrada.TextMarginTop = 0;
            this.txtNumeroNFEntrada.TextPlaceholder = "";
            this.txtNumeroNFEntrada.UseSystemPasswordChar = false;
            this.txtNumeroNFEntrada.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(171, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(77, 15);
            this.label1.TabIndex = 191;
            this.label1.Text = "Data Entrada";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(364, 9);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(68, 15);
            this.label3.TabIndex = 192;
            this.label3.Text = "Cód. Barras";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(14, 67);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(79, 15);
            this.label4.TabIndex = 193;
            this.label4.Text = "Cód. Produto";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(171, 67);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(58, 15);
            this.label5.TabIndex = 194;
            this.label5.Text = "Descrição";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(14, 133);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(71, 15);
            this.label6.TabIndex = 195;
            this.label6.Text = "Quantidade";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(192, 133);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(52, 15);
            this.label7.TabIndex = 196;
            this.label7.Text = "Unidade";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(364, 133);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(82, 15);
            this.label8.TabIndex = 197;
            this.label8.Text = "Valor Unitario";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(14, 207);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(41, 15);
            this.label9.TabIndex = 198;
            this.label9.Text = "Status";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(263, 207);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(84, 15);
            this.label10.TabIndex = 199;
            this.label10.Text = "Rejeitado Por ";
            // 
            // txtDataEntrada
            // 
            this.txtDataEntrada.AcceptsReturn = false;
            this.txtDataEntrada.AcceptsTab = false;
            this.txtDataEntrada.AnimationSpeed = 200;
            this.txtDataEntrada.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDataEntrada.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDataEntrada.BackColor = System.Drawing.Color.Transparent;
            this.txtDataEntrada.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDataEntrada.BackgroundImage")));
            this.txtDataEntrada.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDataEntrada.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDataEntrada.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDataEntrada.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDataEntrada.BorderRadius = 1;
            this.txtDataEntrada.BorderThickness = 1;
            this.txtDataEntrada.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDataEntrada.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDataEntrada.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDataEntrada.DefaultText = "";
            this.txtDataEntrada.Enabled = false;
            this.txtDataEntrada.FillColor = System.Drawing.Color.White;
            this.txtDataEntrada.HideSelection = true;
            this.txtDataEntrada.IconLeft = null;
            this.txtDataEntrada.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDataEntrada.IconPadding = 10;
            this.txtDataEntrada.IconRight = null;
            this.txtDataEntrada.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDataEntrada.Lines = new string[0];
            this.txtDataEntrada.Location = new System.Drawing.Point(174, 27);
            this.txtDataEntrada.MaxLength = 32767;
            this.txtDataEntrada.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDataEntrada.Modified = false;
            this.txtDataEntrada.Multiline = false;
            this.txtDataEntrada.Name = "txtDataEntrada";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDataEntrada.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDataEntrada.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDataEntrada.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDataEntrada.OnIdleState = stateProperties8;
            this.txtDataEntrada.Padding = new System.Windows.Forms.Padding(3);
            this.txtDataEntrada.PasswordChar = '\0';
            this.txtDataEntrada.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDataEntrada.PlaceholderText = "";
            this.txtDataEntrada.ReadOnly = false;
            this.txtDataEntrada.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDataEntrada.SelectedText = "";
            this.txtDataEntrada.SelectionLength = 0;
            this.txtDataEntrada.SelectionStart = 0;
            this.txtDataEntrada.ShortcutsEnabled = false;
            this.txtDataEntrada.Size = new System.Drawing.Size(170, 28);
            this.txtDataEntrada.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDataEntrada.TabIndex = 200;
            this.txtDataEntrada.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDataEntrada.TextMarginBottom = 0;
            this.txtDataEntrada.TextMarginLeft = 3;
            this.txtDataEntrada.TextMarginTop = 0;
            this.txtDataEntrada.TextPlaceholder = "";
            this.txtDataEntrada.UseSystemPasswordChar = false;
            this.txtDataEntrada.WordWrap = true;
            // 
            // txtCodBarras
            // 
            this.txtCodBarras.AcceptsReturn = false;
            this.txtCodBarras.AcceptsTab = false;
            this.txtCodBarras.AnimationSpeed = 200;
            this.txtCodBarras.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCodBarras.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCodBarras.BackColor = System.Drawing.Color.Transparent;
            this.txtCodBarras.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCodBarras.BackgroundImage")));
            this.txtCodBarras.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCodBarras.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCodBarras.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCodBarras.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCodBarras.BorderRadius = 1;
            this.txtCodBarras.BorderThickness = 1;
            this.txtCodBarras.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCodBarras.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodBarras.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCodBarras.DefaultText = "";
            this.txtCodBarras.Enabled = false;
            this.txtCodBarras.FillColor = System.Drawing.Color.White;
            this.txtCodBarras.HideSelection = true;
            this.txtCodBarras.IconLeft = null;
            this.txtCodBarras.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodBarras.IconPadding = 10;
            this.txtCodBarras.IconRight = null;
            this.txtCodBarras.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodBarras.Lines = new string[0];
            this.txtCodBarras.Location = new System.Drawing.Point(367, 27);
            this.txtCodBarras.MaxLength = 32767;
            this.txtCodBarras.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCodBarras.Modified = false;
            this.txtCodBarras.Multiline = false;
            this.txtCodBarras.Name = "txtCodBarras";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodBarras.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCodBarras.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodBarras.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodBarras.OnIdleState = stateProperties12;
            this.txtCodBarras.Padding = new System.Windows.Forms.Padding(3);
            this.txtCodBarras.PasswordChar = '\0';
            this.txtCodBarras.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCodBarras.PlaceholderText = "";
            this.txtCodBarras.ReadOnly = false;
            this.txtCodBarras.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCodBarras.SelectedText = "";
            this.txtCodBarras.SelectionLength = 0;
            this.txtCodBarras.SelectionStart = 0;
            this.txtCodBarras.ShortcutsEnabled = false;
            this.txtCodBarras.Size = new System.Drawing.Size(130, 28);
            this.txtCodBarras.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCodBarras.TabIndex = 201;
            this.txtCodBarras.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCodBarras.TextMarginBottom = 0;
            this.txtCodBarras.TextMarginLeft = 3;
            this.txtCodBarras.TextMarginTop = 0;
            this.txtCodBarras.TextPlaceholder = "";
            this.txtCodBarras.UseSystemPasswordChar = false;
            this.txtCodBarras.WordWrap = true;
            // 
            // txtCodProduto
            // 
            this.txtCodProduto.AcceptsReturn = false;
            this.txtCodProduto.AcceptsTab = false;
            this.txtCodProduto.AnimationSpeed = 200;
            this.txtCodProduto.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCodProduto.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCodProduto.BackColor = System.Drawing.Color.Transparent;
            this.txtCodProduto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCodProduto.BackgroundImage")));
            this.txtCodProduto.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCodProduto.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCodProduto.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCodProduto.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCodProduto.BorderRadius = 1;
            this.txtCodProduto.BorderThickness = 1;
            this.txtCodProduto.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCodProduto.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodProduto.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCodProduto.DefaultText = "";
            this.txtCodProduto.Enabled = false;
            this.txtCodProduto.FillColor = System.Drawing.Color.White;
            this.txtCodProduto.HideSelection = true;
            this.txtCodProduto.IconLeft = null;
            this.txtCodProduto.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodProduto.IconPadding = 10;
            this.txtCodProduto.IconRight = null;
            this.txtCodProduto.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodProduto.Lines = new string[0];
            this.txtCodProduto.Location = new System.Drawing.Point(17, 85);
            this.txtCodProduto.MaxLength = 32767;
            this.txtCodProduto.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCodProduto.Modified = false;
            this.txtCodProduto.Multiline = false;
            this.txtCodProduto.Name = "txtCodProduto";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodProduto.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCodProduto.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodProduto.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodProduto.OnIdleState = stateProperties16;
            this.txtCodProduto.Padding = new System.Windows.Forms.Padding(3);
            this.txtCodProduto.PasswordChar = '\0';
            this.txtCodProduto.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCodProduto.PlaceholderText = "";
            this.txtCodProduto.ReadOnly = false;
            this.txtCodProduto.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCodProduto.SelectedText = "";
            this.txtCodProduto.SelectionLength = 0;
            this.txtCodProduto.SelectionStart = 0;
            this.txtCodProduto.ShortcutsEnabled = false;
            this.txtCodProduto.Size = new System.Drawing.Size(130, 28);
            this.txtCodProduto.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCodProduto.TabIndex = 202;
            this.txtCodProduto.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCodProduto.TextMarginBottom = 0;
            this.txtCodProduto.TextMarginLeft = 3;
            this.txtCodProduto.TextMarginTop = 0;
            this.txtCodProduto.TextPlaceholder = "";
            this.txtCodProduto.UseSystemPasswordChar = false;
            this.txtCodProduto.WordWrap = true;
            // 
            // txtDescricao
            // 
            this.txtDescricao.AcceptsReturn = false;
            this.txtDescricao.AcceptsTab = false;
            this.txtDescricao.AnimationSpeed = 200;
            this.txtDescricao.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDescricao.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDescricao.BackColor = System.Drawing.Color.Transparent;
            this.txtDescricao.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDescricao.BackgroundImage")));
            this.txtDescricao.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDescricao.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDescricao.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDescricao.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDescricao.BorderRadius = 1;
            this.txtDescricao.BorderThickness = 1;
            this.txtDescricao.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDescricao.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDescricao.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDescricao.DefaultText = "";
            this.txtDescricao.Enabled = false;
            this.txtDescricao.FillColor = System.Drawing.Color.White;
            this.txtDescricao.HideSelection = true;
            this.txtDescricao.IconLeft = null;
            this.txtDescricao.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDescricao.IconPadding = 10;
            this.txtDescricao.IconRight = null;
            this.txtDescricao.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDescricao.Lines = new string[0];
            this.txtDescricao.Location = new System.Drawing.Point(174, 85);
            this.txtDescricao.MaxLength = 32767;
            this.txtDescricao.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDescricao.Modified = false;
            this.txtDescricao.Multiline = false;
            this.txtDescricao.Name = "txtDescricao";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDescricao.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDescricao.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDescricao.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDescricao.OnIdleState = stateProperties20;
            this.txtDescricao.Padding = new System.Windows.Forms.Padding(3);
            this.txtDescricao.PasswordChar = '\0';
            this.txtDescricao.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDescricao.PlaceholderText = "";
            this.txtDescricao.ReadOnly = false;
            this.txtDescricao.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDescricao.SelectedText = "";
            this.txtDescricao.SelectionLength = 0;
            this.txtDescricao.SelectionStart = 0;
            this.txtDescricao.ShortcutsEnabled = false;
            this.txtDescricao.Size = new System.Drawing.Size(323, 28);
            this.txtDescricao.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDescricao.TabIndex = 203;
            this.txtDescricao.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDescricao.TextMarginBottom = 0;
            this.txtDescricao.TextMarginLeft = 3;
            this.txtDescricao.TextMarginTop = 0;
            this.txtDescricao.TextPlaceholder = "";
            this.txtDescricao.UseSystemPasswordChar = false;
            this.txtDescricao.WordWrap = true;
            // 
            // txtQuantidade
            // 
            this.txtQuantidade.AcceptsReturn = false;
            this.txtQuantidade.AcceptsTab = false;
            this.txtQuantidade.AnimationSpeed = 200;
            this.txtQuantidade.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtQuantidade.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtQuantidade.BackColor = System.Drawing.Color.Transparent;
            this.txtQuantidade.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtQuantidade.BackgroundImage")));
            this.txtQuantidade.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtQuantidade.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtQuantidade.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtQuantidade.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtQuantidade.BorderRadius = 1;
            this.txtQuantidade.BorderThickness = 1;
            this.txtQuantidade.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtQuantidade.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantidade.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtQuantidade.DefaultText = "";
            this.txtQuantidade.Enabled = false;
            this.txtQuantidade.FillColor = System.Drawing.Color.White;
            this.txtQuantidade.HideSelection = true;
            this.txtQuantidade.IconLeft = null;
            this.txtQuantidade.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantidade.IconPadding = 10;
            this.txtQuantidade.IconRight = null;
            this.txtQuantidade.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantidade.Lines = new string[0];
            this.txtQuantidade.Location = new System.Drawing.Point(17, 151);
            this.txtQuantidade.MaxLength = 32767;
            this.txtQuantidade.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtQuantidade.Modified = false;
            this.txtQuantidade.Multiline = false;
            this.txtQuantidade.Name = "txtQuantidade";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantidade.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtQuantidade.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantidade.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantidade.OnIdleState = stateProperties24;
            this.txtQuantidade.Padding = new System.Windows.Forms.Padding(3);
            this.txtQuantidade.PasswordChar = '\0';
            this.txtQuantidade.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQuantidade.PlaceholderText = "";
            this.txtQuantidade.ReadOnly = false;
            this.txtQuantidade.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtQuantidade.SelectedText = "";
            this.txtQuantidade.SelectionLength = 0;
            this.txtQuantidade.SelectionStart = 0;
            this.txtQuantidade.ShortcutsEnabled = false;
            this.txtQuantidade.Size = new System.Drawing.Size(130, 28);
            this.txtQuantidade.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtQuantidade.TabIndex = 204;
            this.txtQuantidade.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtQuantidade.TextMarginBottom = 0;
            this.txtQuantidade.TextMarginLeft = 3;
            this.txtQuantidade.TextMarginTop = 0;
            this.txtQuantidade.TextPlaceholder = "";
            this.txtQuantidade.UseSystemPasswordChar = false;
            this.txtQuantidade.WordWrap = true;
            // 
            // txtUnidade
            // 
            this.txtUnidade.AcceptsReturn = false;
            this.txtUnidade.AcceptsTab = false;
            this.txtUnidade.AnimationSpeed = 200;
            this.txtUnidade.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUnidade.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUnidade.BackColor = System.Drawing.Color.Transparent;
            this.txtUnidade.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUnidade.BackgroundImage")));
            this.txtUnidade.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUnidade.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUnidade.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUnidade.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUnidade.BorderRadius = 1;
            this.txtUnidade.BorderThickness = 1;
            this.txtUnidade.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUnidade.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnidade.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUnidade.DefaultText = "";
            this.txtUnidade.Enabled = false;
            this.txtUnidade.FillColor = System.Drawing.Color.White;
            this.txtUnidade.HideSelection = true;
            this.txtUnidade.IconLeft = null;
            this.txtUnidade.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnidade.IconPadding = 10;
            this.txtUnidade.IconRight = null;
            this.txtUnidade.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnidade.Lines = new string[0];
            this.txtUnidade.Location = new System.Drawing.Point(195, 151);
            this.txtUnidade.MaxLength = 32767;
            this.txtUnidade.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUnidade.Modified = false;
            this.txtUnidade.Multiline = false;
            this.txtUnidade.Name = "txtUnidade";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnidade.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUnidade.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnidade.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnidade.OnIdleState = stateProperties28;
            this.txtUnidade.Padding = new System.Windows.Forms.Padding(3);
            this.txtUnidade.PasswordChar = '\0';
            this.txtUnidade.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUnidade.PlaceholderText = "";
            this.txtUnidade.ReadOnly = false;
            this.txtUnidade.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUnidade.SelectedText = "";
            this.txtUnidade.SelectionLength = 0;
            this.txtUnidade.SelectionStart = 0;
            this.txtUnidade.ShortcutsEnabled = false;
            this.txtUnidade.Size = new System.Drawing.Size(130, 28);
            this.txtUnidade.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUnidade.TabIndex = 205;
            this.txtUnidade.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUnidade.TextMarginBottom = 0;
            this.txtUnidade.TextMarginLeft = 3;
            this.txtUnidade.TextMarginTop = 0;
            this.txtUnidade.TextPlaceholder = "";
            this.txtUnidade.UseSystemPasswordChar = false;
            this.txtUnidade.WordWrap = true;
            // 
            // txtValorUnitario
            // 
            this.txtValorUnitario.AcceptsReturn = false;
            this.txtValorUnitario.AcceptsTab = false;
            this.txtValorUnitario.AnimationSpeed = 200;
            this.txtValorUnitario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtValorUnitario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtValorUnitario.BackColor = System.Drawing.Color.Transparent;
            this.txtValorUnitario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtValorUnitario.BackgroundImage")));
            this.txtValorUnitario.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtValorUnitario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtValorUnitario.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtValorUnitario.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtValorUnitario.BorderRadius = 1;
            this.txtValorUnitario.BorderThickness = 1;
            this.txtValorUnitario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtValorUnitario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtValorUnitario.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtValorUnitario.DefaultText = "";
            this.txtValorUnitario.Enabled = false;
            this.txtValorUnitario.FillColor = System.Drawing.Color.White;
            this.txtValorUnitario.HideSelection = true;
            this.txtValorUnitario.IconLeft = null;
            this.txtValorUnitario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtValorUnitario.IconPadding = 10;
            this.txtValorUnitario.IconRight = null;
            this.txtValorUnitario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtValorUnitario.Lines = new string[0];
            this.txtValorUnitario.Location = new System.Drawing.Point(367, 151);
            this.txtValorUnitario.MaxLength = 32767;
            this.txtValorUnitario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtValorUnitario.Modified = false;
            this.txtValorUnitario.Multiline = false;
            this.txtValorUnitario.Name = "txtValorUnitario";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtValorUnitario.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtValorUnitario.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtValorUnitario.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtValorUnitario.OnIdleState = stateProperties32;
            this.txtValorUnitario.Padding = new System.Windows.Forms.Padding(3);
            this.txtValorUnitario.PasswordChar = '\0';
            this.txtValorUnitario.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtValorUnitario.PlaceholderText = "";
            this.txtValorUnitario.ReadOnly = false;
            this.txtValorUnitario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtValorUnitario.SelectedText = "";
            this.txtValorUnitario.SelectionLength = 0;
            this.txtValorUnitario.SelectionStart = 0;
            this.txtValorUnitario.ShortcutsEnabled = false;
            this.txtValorUnitario.Size = new System.Drawing.Size(130, 28);
            this.txtValorUnitario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtValorUnitario.TabIndex = 206;
            this.txtValorUnitario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtValorUnitario.TextMarginBottom = 0;
            this.txtValorUnitario.TextMarginLeft = 3;
            this.txtValorUnitario.TextMarginTop = 0;
            this.txtValorUnitario.TextPlaceholder = "";
            this.txtValorUnitario.UseSystemPasswordChar = false;
            this.txtValorUnitario.WordWrap = true;
            // 
            // txtStatus
            // 
            this.txtStatus.AcceptsReturn = false;
            this.txtStatus.AcceptsTab = false;
            this.txtStatus.AnimationSpeed = 200;
            this.txtStatus.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStatus.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStatus.BackColor = System.Drawing.Color.Transparent;
            this.txtStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStatus.BackgroundImage")));
            this.txtStatus.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtStatus.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStatus.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtStatus.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStatus.BorderRadius = 1;
            this.txtStatus.BorderThickness = 1;
            this.txtStatus.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStatus.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStatus.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtStatus.DefaultText = "";
            this.txtStatus.Enabled = false;
            this.txtStatus.FillColor = System.Drawing.Color.White;
            this.txtStatus.HideSelection = true;
            this.txtStatus.IconLeft = null;
            this.txtStatus.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStatus.IconPadding = 10;
            this.txtStatus.IconRight = null;
            this.txtStatus.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStatus.Lines = new string[0];
            this.txtStatus.Location = new System.Drawing.Point(17, 225);
            this.txtStatus.MaxLength = 32767;
            this.txtStatus.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStatus.Modified = false;
            this.txtStatus.Multiline = false;
            this.txtStatus.Name = "txtStatus";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStatus.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStatus.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStatus.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStatus.OnIdleState = stateProperties36;
            this.txtStatus.Padding = new System.Windows.Forms.Padding(3);
            this.txtStatus.PasswordChar = '\0';
            this.txtStatus.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStatus.PlaceholderText = "";
            this.txtStatus.ReadOnly = false;
            this.txtStatus.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStatus.SelectedText = "";
            this.txtStatus.SelectionLength = 0;
            this.txtStatus.SelectionStart = 0;
            this.txtStatus.ShortcutsEnabled = false;
            this.txtStatus.Size = new System.Drawing.Size(231, 28);
            this.txtStatus.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStatus.TabIndex = 207;
            this.txtStatus.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStatus.TextMarginBottom = 0;
            this.txtStatus.TextMarginLeft = 3;
            this.txtStatus.TextMarginTop = 0;
            this.txtStatus.TextPlaceholder = "";
            this.txtStatus.UseSystemPasswordChar = false;
            this.txtStatus.WordWrap = true;
            // 
            // txtRejeitatoPor
            // 
            this.txtRejeitatoPor.AcceptsReturn = false;
            this.txtRejeitatoPor.AcceptsTab = false;
            this.txtRejeitatoPor.AnimationSpeed = 200;
            this.txtRejeitatoPor.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRejeitatoPor.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRejeitatoPor.BackColor = System.Drawing.Color.Transparent;
            this.txtRejeitatoPor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRejeitatoPor.BackgroundImage")));
            this.txtRejeitatoPor.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtRejeitatoPor.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRejeitatoPor.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtRejeitatoPor.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtRejeitatoPor.BorderRadius = 1;
            this.txtRejeitatoPor.BorderThickness = 1;
            this.txtRejeitatoPor.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRejeitatoPor.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRejeitatoPor.DefaultFont = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRejeitatoPor.DefaultText = "";
            this.txtRejeitatoPor.Enabled = false;
            this.txtRejeitatoPor.FillColor = System.Drawing.Color.White;
            this.txtRejeitatoPor.HideSelection = true;
            this.txtRejeitatoPor.IconLeft = null;
            this.txtRejeitatoPor.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRejeitatoPor.IconPadding = 10;
            this.txtRejeitatoPor.IconRight = null;
            this.txtRejeitatoPor.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRejeitatoPor.Lines = new string[0];
            this.txtRejeitatoPor.Location = new System.Drawing.Point(266, 225);
            this.txtRejeitatoPor.MaxLength = 32767;
            this.txtRejeitatoPor.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRejeitatoPor.Modified = false;
            this.txtRejeitatoPor.Multiline = false;
            this.txtRejeitatoPor.Name = "txtRejeitatoPor";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRejeitatoPor.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRejeitatoPor.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRejeitatoPor.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRejeitatoPor.OnIdleState = stateProperties40;
            this.txtRejeitatoPor.Padding = new System.Windows.Forms.Padding(3);
            this.txtRejeitatoPor.PasswordChar = '\0';
            this.txtRejeitatoPor.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRejeitatoPor.PlaceholderText = "";
            this.txtRejeitatoPor.ReadOnly = false;
            this.txtRejeitatoPor.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRejeitatoPor.SelectedText = "";
            this.txtRejeitatoPor.SelectionLength = 0;
            this.txtRejeitatoPor.SelectionStart = 0;
            this.txtRejeitatoPor.ShortcutsEnabled = false;
            this.txtRejeitatoPor.Size = new System.Drawing.Size(231, 28);
            this.txtRejeitatoPor.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRejeitatoPor.TabIndex = 208;
            this.txtRejeitatoPor.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRejeitatoPor.TextMarginBottom = 0;
            this.txtRejeitatoPor.TextMarginLeft = 3;
            this.txtRejeitatoPor.TextMarginTop = 0;
            this.txtRejeitatoPor.TextPlaceholder = "";
            this.txtRejeitatoPor.UseSystemPasswordChar = false;
            this.txtRejeitatoPor.WordWrap = true;
            // 
            // btnFechar
            // 
            this.btnFechar.AllowAnimations = true;
            this.btnFechar.AllowMouseEffects = true;
            this.btnFechar.AllowToggling = false;
            this.btnFechar.AnimationSpeed = 200;
            this.btnFechar.AutoGenerateColors = false;
            this.btnFechar.AutoRoundBorders = false;
            this.btnFechar.AutoSizeLeftIcon = true;
            this.btnFechar.AutoSizeRightIcon = true;
            this.btnFechar.BackColor = System.Drawing.Color.Transparent;
            this.btnFechar.BackColor1 = System.Drawing.Color.Transparent;
            this.btnFechar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFechar.BackgroundImage")));
            this.btnFechar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.ButtonText = "(Esc) Fechar ";
            this.btnFechar.ButtonTextMarginLeft = 0;
            this.btnFechar.ColorContrastOnClick = 45;
            this.btnFechar.ColorContrastOnHover = 45;
            this.btnFechar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnFechar.CustomizableEdges = borderEdges1;
            this.btnFechar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFechar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFechar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFechar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFechar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFechar.Font = new System.Drawing.Font("Calibri", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFechar.ForeColor = System.Drawing.Color.Black;
            this.btnFechar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFechar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFechar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFechar.IconMarginLeft = 11;
            this.btnFechar.IconPadding = 10;
            this.btnFechar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFechar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFechar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFechar.IconSize = 25;
            this.btnFechar.IdleBorderColor = System.Drawing.Color.Black;
            this.btnFechar.IdleBorderRadius = 1;
            this.btnFechar.IdleBorderThickness = 1;
            this.btnFechar.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnFechar.IdleIconLeftImage = null;
            this.btnFechar.IdleIconRightImage = null;
            this.btnFechar.IndicateFocus = false;
            this.btnFechar.Location = new System.Drawing.Point(160, 273);
            this.btnFechar.Name = "btnFechar";
            this.btnFechar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFechar.OnDisabledState.BorderRadius = 1;
            this.btnFechar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.OnDisabledState.BorderThickness = 1;
            this.btnFechar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFechar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFechar.OnDisabledState.IconLeftImage = null;
            this.btnFechar.OnDisabledState.IconRightImage = null;
            this.btnFechar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFechar.onHoverState.BorderRadius = 1;
            this.btnFechar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.onHoverState.BorderThickness = 1;
            this.btnFechar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFechar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFechar.onHoverState.IconLeftImage = null;
            this.btnFechar.onHoverState.IconRightImage = null;
            this.btnFechar.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnFechar.OnIdleState.BorderRadius = 1;
            this.btnFechar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.OnIdleState.BorderThickness = 1;
            this.btnFechar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnFechar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnFechar.OnIdleState.IconLeftImage = null;
            this.btnFechar.OnIdleState.IconRightImage = null;
            this.btnFechar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFechar.OnPressedState.BorderRadius = 1;
            this.btnFechar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFechar.OnPressedState.BorderThickness = 1;
            this.btnFechar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFechar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFechar.OnPressedState.IconLeftImage = null;
            this.btnFechar.OnPressedState.IconRightImage = null;
            this.btnFechar.Size = new System.Drawing.Size(187, 39);
            this.btnFechar.TabIndex = 209;
            this.btnFechar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFechar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFechar.TextMarginLeft = 0;
            this.btnFechar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFechar.UseDefaultRadiusAndThickness = true;
            this.btnFechar.Click += new System.EventHandler(this.btnFechar_Click);
            // 
            // logoSistema1
            // 
            this.logoSistema1.Location = new System.Drawing.Point(407, 289);
            this.logoSistema1.Name = "logoSistema1";
            this.logoSistema1.Size = new System.Drawing.Size(107, 39);
            this.logoSistema1.TabIndex = 210;
            // 
            // Forms_ConsultaEstoqueDetalhada
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(516, 328);
            this.Controls.Add(this.logoSistema1);
            this.Controls.Add(this.btnFechar);
            this.Controls.Add(this.txtRejeitatoPor);
            this.Controls.Add(this.txtStatus);
            this.Controls.Add(this.txtValorUnitario);
            this.Controls.Add(this.txtUnidade);
            this.Controls.Add(this.txtQuantidade);
            this.Controls.Add(this.txtDescricao);
            this.Controls.Add(this.txtCodProduto);
            this.Controls.Add(this.txtCodBarras);
            this.Controls.Add(this.txtDataEntrada);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtNumeroNFEntrada);
            this.Controls.Add(this.label2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.Name = "Forms_ConsultaEstoqueDetalhada";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Consulta Detalhada";
            this.Load += new System.EventHandler(this.Forms_ConsultaEstoqueDetalhada_Load);
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Forms_ConsultaEstoqueDetalhada_KeyDown);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtNumeroNFEntrada;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private Bunifu.UI.WinForms.BunifuTextBox txtDataEntrada;
        private Bunifu.UI.WinForms.BunifuTextBox txtCodBarras;
        private Bunifu.UI.WinForms.BunifuTextBox txtCodProduto;
        private Bunifu.UI.WinForms.BunifuTextBox txtDescricao;
        private Bunifu.UI.WinForms.BunifuTextBox txtQuantidade;
        private Bunifu.UI.WinForms.BunifuTextBox txtUnidade;
        private Bunifu.UI.WinForms.BunifuTextBox txtValorUnitario;
        private Bunifu.UI.WinForms.BunifuTextBox txtStatus;
        private Bunifu.UI.WinForms.BunifuTextBox txtRejeitatoPor;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFechar;
        private LogoSistema logoSistema1;
    }
}